service : test-deploy

plugins:
  - serverless-python-requirements
provider:
 name: aws
 runtime: python3.7
 region : us-east-1
 deploymentBucket:
  name : insight-deploy-kolb
 iamRoleStatements:
  - Effect : Allow
    Action:
     - s3.GetObject
    Resource:
     - "arn:aws:s3:::insight-deploy-kolb/*"

custom:
 pythonRequirements:
  slim : true

functions:
 assembly-rating:
  name: assembly-rating-function
  description : deploy assembly rating ml model
  handler : main.lambda_handler
  events :
   - http : POST /predictadult
